import type { Team, CarPerformance, ComponentAllocation, RndUpgrade } from '@/types/team'
import { calculateOverallRating } from './car-performance'
import { getGridPenalty } from './component-lifecycle'

/**
 * Pure derivations for the Factory page. No side effects; no PRNG needed for
 * visual-only values (correlationDelta uses a small deterministic hash so the
 * number is stable across renders without carrying a PRNG in UI code).
 */

/** Axis order used by the radar. Kept in one place so UI + helpers agree. */
export const FACTORY_AXIS_ORDER: Array<keyof CarPerformance> = [
  'downforce',
  'straightSpeed',
  'braking',
  'cornering',
  'reliability',
  'tireManagement',
]

const PEER_FALLBACK = 70

/** Field-average axis values across every team *except* the player. */
export function peerAveragedAxes(teams: Team[], playerTeamId: string): number[] {
  const peers = teams.filter((t) => t.id !== playerTeamId)
  if (peers.length === 0) {
    return FACTORY_AXIS_ORDER.map(() => PEER_FALLBACK)
  }
  return FACTORY_AXIS_ORDER.map((axis) => {
    const sum = peers.reduce((acc, t) => acc + t.car[axis], 0)
    return Math.round(sum / peers.length)
  })
}

/** Player team's constructor rank, clamped to [1, 11]. */
export function peerRank(teams: Team[], playerTeamId: string): number {
  const team = teams.find((t) => t.id === playerTeamId)
  if (!team) return 11
  return Math.max(1, Math.min(11, team.constructorPosition))
}

/**
 * Approximate lap-time gap to the championship leader, in seconds. Derived
 * from the OVR rating difference: each OVR point maps to roughly ~0.03s per
 * lap around a mid-length circuit. Negative when the player trails; 0 when
 * leading. This is a presentation-layer estimate — the authoritative gap is
 * generated by the race simulator per-circuit.
 */
export function deltaVsLeaderSeconds(teams: Team[], playerTeamId: string): number {
  const player = teams.find((t) => t.id === playerTeamId)
  if (!player) return 0
  const playerOvr = calculateOverallRating(player.car)
  const leaderOvr = teams.reduce(
    (best, t) => Math.max(best, calculateOverallRating(t.car)),
    playerOvr,
  )
  if (leaderOvr <= playerOvr) return 0
  const gap = leaderOvr - playerOvr
  return -Number((gap * 0.03).toFixed(2))
}

/** Fleet health classification based on component usage vs limits. */
export type FleetHealth = 'NOMINAL' | 'AT RISK' | 'CRITICAL'

export function fleetHealth(components: ComponentAllocation[]): FleetHealth {
  if (components.some((c) => c.used >= c.limit)) return 'CRITICAL'
  if (components.some((c) => c.used >= c.limit - 1)) return 'AT RISK'
  return 'NOMINAL'
}

/**
 * Project the next likely component change round. Picks the element with the
 * highest used/limit ratio that still has *some* usage (i.e. is being worn
 * down), and estimates races-until-next-change from the current usage rate.
 * Returns null when no component is within one unit of its limit.
 */
export function projectNextChange(
  components: ComponentAllocation[],
  currentRound: number,
  totalRaces: number,
): { element: ComponentAllocation['element']; round: number } | null {
  const candidates = components
    .filter((c) => c.limit - c.used <= 1 || c.used / c.limit >= 0.75)
    .map((c) => ({ c, ratio: c.used / Math.max(1, c.limit) }))
    .sort((a, b) => b.ratio - a.ratio)

  if (candidates.length === 0) return null
  const picked = candidates[0].c
  // Use racing-cadence estimate: racesRemaining = max(1, totalRaces - currentRound).
  // Next change lands roughly at the midpoint between now and season end, biased
  // by how close the component is to its limit.
  const racesLeft = Math.max(1, totalRaces - currentRound)
  const proximity = Math.max(0, picked.limit - picked.used)
  const offset = proximity === 0 ? 1 : Math.max(1, Math.round(racesLeft / (picked.limit * 2)))
  return {
    element: picked.element,
    round: Math.min(totalRaces, currentRound + offset),
  }
}

/** Total projected grid loss assuming every currently over-limit element is swapped. */
export function projectedGridLoss(components: ComponentAllocation[]): number {
  return components.reduce((acc, c) => acc + (c.used >= c.limit ? getGridPenalty(c) : 0), 0)
}

/**
 * F1 Aerodynamic Testing Restriction (ATR) sliding scale for the 2026 ruleset:
 * champion gets 70% of the baseline testing allowance; last place gets 100%.
 * Linear interpolation across the 11-constructor grid.
 */
export function atrCoefficientForPosition(constructorPosition: number): number {
  const clamped = Math.max(1, Math.min(11, constructorPosition))
  const min = 0.7
  const max = 1.0
  // pos 1 → 0.7, pos 11 → 1.0
  const t = (clamped - 1) / 10
  return Number((min + (max - min) * t).toFixed(2))
}

/**
 * Correlation delta — how well wind-tunnel / CFD predictions match on-track
 * performance, expressed as a percentage. Deterministic hash of team id +
 * round keeps it stable across renders without carrying a PRNG into the UI.
 * Bounded to ±5%.
 */
export function correlationDelta(teamId: string, round: number): number {
  let h = round
  for (let i = 0; i < teamId.length; i++) {
    h = (h * 31 + teamId.charCodeAt(i)) | 0
  }
  // Map hash to [-5, 5] with one decimal place.
  const scaled = ((Math.abs(h) % 101) - 50) / 10
  return Number(scaled.toFixed(1))
}

/**
 * Next scheduled upgrade delivery. Picks the in-progress upgrade with the
 * fewest remaining development races. Returns the predicted delivery round.
 */
export function nextDeliveryRound(
  upgrades: RndUpgrade[],
  currentRound: number,
): { upgradeId: string; round: number } | null {
  const active = upgrades
    .filter((u) => u.status === 'in-progress')
    .map((u) => {
      const remaining = Math.max(1, Math.ceil(((100 - u.progress) / 100) * u.developmentRaces))
      return { u, remaining }
    })
    .sort((a, b) => a.remaining - b.remaining)

  if (active.length === 0) return null
  const { u, remaining } = active[0]
  return { upgradeId: u.id, round: currentRound + remaining }
}

/**
 * Days remaining until the next ATR testing window resets. The 2026 reg uses
 * a rolling 14-day window — we approximate it here from the race cadence
 * (~14 days between rounds in-season).
 */
export function windowResetsIn(currentRound: number): number {
  // Deterministic derivation: rounds 1–22 map to 0–13 day countdowns.
  return (14 - (currentRound * 2) % 14) % 14
}

/**
 * Mean time between failures, in laps. Derived from car reliability and the
 * average component wear ratio (worn components fail sooner). The curve is
 * tuned so that a fresh 80-reliability car sits around ~18 laps (matching
 * the broadcast-card placeholder used during Phase A) and a heavily-worn
 * 50-reliability car falls to single digits.
 */
export function reliabilityMtbf(
  car: CarPerformance,
  components: ComponentAllocation[],
): number {
  const rel = Math.max(0, Math.min(100, car.reliability)) / 100
  const wearRatio = components.length === 0
    ? 0
    : components.reduce((acc, c) => acc + c.used / Math.max(1, c.limit), 0) / components.length
  // Base laps at 100% reliability, 0% wear: 30. Drops as reliability falls
  // and wear rises. Never below 1 lap.
  const base = 6 + rel * 24 // 6 → 30
  const wearPenalty = 1 - wearRatio * 0.4 // 1.0 → 0.6
  return Number(Math.max(1, base * wearPenalty).toFixed(1))
}

/**
 * Deterministic 14-entry daily booking histogram (values in [0, 1]) for the
 * wind-tunnel or CFD bars on the Factory aero card. Seeded by team id +
 * round so the same input always yields the same output, and scaled by the
 * season usage ratio so a team that's spent heavily shows denser bars.
 *
 * This is a presentation-layer derivation — no daily tick is actually
 * simulated. If a future wave persists real per-day bookings, this helper
 * can be retired in one step.
 */
export function deterministicAeroHistory(
  teamId: string,
  round: number,
  usageRatio: number,
): number[] {
  const ratio = Math.max(0, Math.min(1, usageRatio))
  const out: number[] = []
  let h = round * 2654435761
  for (let i = 0; i < teamId.length; i++) {
    h = (h ^ teamId.charCodeAt(i)) * 16777619
  }
  for (let d = 0; d < 14; d++) {
    // xorshift-style scramble so adjacent days don't correlate.
    h ^= h << 13
    h ^= h >>> 17
    h ^= h << 5
    const frac = ((h >>> 0) % 1000) / 1000
    // Quiet days (weekend / blackout) when the scramble lands low.
    const val = frac < 0.15 ? 0 : Math.max(0, Math.min(1, frac * ratio * 1.3))
    out.push(Number(val.toFixed(2)))
  }
  return out
}
