import type { CalibrationProfile } from '@/types/calibration'

import abuDhabi from './abu-dhabi.json'
import austin from './austin.json'
import bahrain from './bahrain.json'
import baku from './baku.json'
import barcelona from './barcelona.json'
import imola from './imola.json'
import interlagos from './interlagos.json'
import jeddah from './jeddah.json'
import lasVegas from './las-vegas.json'
import melbourne from './melbourne.json'
import mexico from './mexico.json'
import miami from './miami.json'
import monaco from './monaco.json'
import montreal from './montreal.json'
import monza from './monza.json'
import shanghai from './shanghai.json'
import silverstone from './silverstone.json'
import singapore from './singapore.json'
import spa from './spa.json'
import spielberg from './spielberg.json'
import suzuka from './suzuka.json'
import zandvoort from './zandvoort.json'

// ---------------------------------------------------------------------------
// Built-in profile array
//
// Generated by `npm run sync:openf1 -- --year=<season>` against api.openf1.org.
// Ship these as static imports so engines never block on network I/O and the
// bundle stays fully deterministic.
//
// When the sync script produces a new JSON under this directory, append an
// import + array entry here. The registry (index.ts) auto-hydrates from this
// list at module init.
// ---------------------------------------------------------------------------

export const BUILT_IN_CALIBRATION_PROFILES: readonly CalibrationProfile[] = [
  abuDhabi,
  austin,
  bahrain,
  baku,
  barcelona,
  imola,
  interlagos,
  jeddah,
  lasVegas,
  melbourne,
  mexico,
  miami,
  monaco,
  montreal,
  monza,
  shanghai,
  silverstone,
  singapore,
  spa,
  spielberg,
  suzuka,
  zandvoort,
] as CalibrationProfile[]
