// Paddock page fake data — aligned with strategy page, Monterra GP completed, heading to Round 8
window.PADDOCK_DATA = {
  team: {
    id: "NV",
    name: "NOVARA RACING",
    color: "#E63946",
    dark: "#9B1C2A",
    constructorPosition: 2,
    carRating: 86,
    morale: 78,
    prestige: 62,
    budget: { cap: 135, spent: 92.6, remaining: 42.4, penaltyRisk: false },
    seasonForm: [3, 2, 4, 1, 2, 3, 1], // last 7 races constructor positions per round
  },
  nextRace: {
    round: 8,
    name: "IMOLA COAST",
    country: "Italy",
    date: "MAY 12",
    daysOut: 14,
    air: 22, track: 34, rain: 35,
    sessions: [
      { k: "FP1", d: "FRI 13:30" },
      { k: "FP2", d: "FRI 17:00" },
      { k: "FP3", d: "SAT 12:30" },
      { k: "QUAL", d: "SAT 16:00" },
      { k: "RACE", d: "SUN 15:00" },
    ],
  },
  drivers: [
    {
      id: "VSK", first: "Viktor", last: "Stern", num: 16, nat: "SWE",
      wdc: 2, pts: 143, lastPos: 1, podiums: 4, wins: 2, poles: 1,
      mood: { motivation: 84, confidence: 81, frustration: 18 },
      moodLabel: "MOTIVATED",
      form: [3, 2, 1, 1, 2, 1, 1], // last 7 races finishing positions
      contract: "2027",
      rating: 88,
    },
    {
      id: "SOR", first: "Soren", last: "Rask", num: 88, nat: "DEN",
      wdc: 11, pts: 45, lastPos: 19, podiums: 0, wins: 0, poles: 0,
      mood: { motivation: 42, confidence: 38, frustration: 74 },
      moodLabel: "FRUSTRATED",
      form: [13, 11, 15, 12, 14, 17, 19],
      contract: "2026",
      rating: 72,
    },
  ],
  standings: [
    { pos: 1, team: "AX", name: "AXIOM MOTORSPORT",  pts: 168, color: "#00D4E0", delta: 0 },
    { pos: 2, team: "NV", name: "NOVARA RACING",     pts: 143, color: "#E63946", delta: +1 },
    { pos: 3, team: "MR", name: "MERIDIAN GP",       pts: 128, color: "#FFC300", delta: -1 },
    { pos: 4, team: "VT", name: "VERTEX WORKS",      pts: 96,  color: "#7A5FFF", delta: 0 },
    { pos: 5, team: "KS", name: "KESTREL RACING",    pts: 74,  color: "#2EC27E", delta: +2 },
    { pos: 6, team: "OB", name: "OBSIDIAN GP",       pts: 58,  color: "#EAEAEA", delta: -1 },
  ],
  feed: [
    { id: "e1", round: 7, sev: "breaking", head: "AXIOM PROTEST OVER FRONT WING FLEX REJECTED", body: "FIA technical delegate cleared all teams post-Monterra. No grid penalty applied.", resolved: true },
    { id: "e2", round: 7, sev: "decision", head: "RASK REQUESTS ENGINEER RESHUFFLE", body: "Soren has asked for Peter Proshareau to be reassigned to his car. His current engineer disagrees with the strategy call from Monterra.", options: [ { id: "yes", t: "Approve reshuffle" }, { id: "no", t: "Decline — keep pair" }, { id: "talk", t: "Speak with Soren first" } ] },
    { id: "e3", round: 7, sev: "technical", head: "FLOOR UPGRADE PASSES WIND TUNNEL TARGETS", body: "New floor package delivers +0.18s per lap estimated. Scheduled for R09 Hungaroring debut pending CFD validation.", resolved: true },
    { id: "e4", round: 7, sev: "rumor", head: "RIEVEN SEEKING EXIT CLAUSE — VERTEX STANDS FIRM", body: "Italian press reports Naoki Rieven is exploring options for 2027. Source close to Vertex denies any active talks.", resolved: true },
    { id: "e5", round: 6, sev: "decision", head: "SPONSOR RENEWAL NEGOTIATION", body: "TRANSMIT Ltd offering a 3-year extension at 12% uplift. Due to expire end of season.", options: [ { id: "sign", t: "Sign extension" }, { id: "counter", t: "Counter-offer" }, { id: "decline", t: "Decline" } ] },
    { id: "e6", round: 6, sev: "news", head: "BOARD APPROVED 2027 POWER UNIT PARTNERSHIP", body: "Long-form agreement with Hexon Automotive ratified by the board. Supply begins R01 2027." },
    { id: "e7", round: 5, sev: "breaking", head: "GRID PENALTY APPLIED TO AZAROV", body: "Obsidian GP lost P9 to impeding. Grid drop carries to Imola Coast." },
  ],
  recommendations: [
    { id: "r1", role: "TD", roleName: "Technical Director", text: "Shift 6M from chassis to aero — wind tunnel flagged marginal gains on rear diffuser rework. Expected +0.08s/lap.", applicable: true },
    { id: "r2", role: "RE", roleName: "Race Engineer", text: "Rask's tire deg is running 18% hotter than Stern across long runs. Recommend cooling duct adjustment for FP1.", applicable: true },
    { id: "r3", role: "CD", roleName: "Commercial Director", text: "Sponsor activation due before round 8 — media day with TRANSMIT Ltd recommended to protect renewal leverage.", applicable: true },
    { id: "r4", role: "TM", roleName: "Team Manager", text: "Morale dip in garage — Rask's side. Propose a team-building briefing before Friday.", applicable: false },
  ],
  departments: [
    { role: "TD", roleName: "Technical Director",    name: "Peter Proshareau",  skill: 84, contract: "2028" },
    { role: "RE", roleName: "Race Engineer",         name: "Tom Stadlund",      skill: 78, contract: "2026" },
    { role: "CD", roleName: "Commercial Director",   name: "Louise McEwen",     skill: 81, contract: "2027" },
    { role: "TM", roleName: "Team Manager",          name: "Andrea Mayfield",   skill: 87, contract: "2029" },
  ],
  upcoming: [
    { when: "MON", label: "Sponsor media day · TRANSMIT Ltd" },
    { when: "TUE", label: "R&D review · diffuser v3" },
    { when: "WED", label: "Factory walk-through with board" },
    { when: "THU", label: "Travel to Imola · Freight departs 09:00" },
    { when: "FRI", label: "FP1 · 13:30 local" },
  ],
};
