window.DRIVERS_DATA = {
  team: {
    name: "VANTAGE GP",
    code: "VAN",
    color: "oklch(0.62 0.20 265)",
    dark: "oklch(0.28 0.12 265)",
    season: 2026,
    currentRound: 8,
    constructorPosition: 2,
    nextRound: { id: "R09", name: "MONTRÉAL · CIRCUIT GILLES VILLENEUVE" },
  },
  offenceLabels: {
    causingCollision: "Causing a collision",
    unsafeRelease: "Unsafe release",
    speedingPitLane: "Speeding in pit lane",
    ignoredFlags: "Ignored flag instructions",
    blockingQualifying: "Impeding in qualifying",
    excessiveTrackLimits: "Repeated track limits",
    drivingDangerously: "Driving without due care",
    falseStart: "False start / jump start",
    formationLapInfraction: "Formation lap infraction",
  },
  roster: [
    {
      slot: "CAR-01",
      firstName: "Max",
      lastName: "Verstappen",
      shortName: "VER",
      natCode: "NED",
      age: 28,
      raceNumber: 1,
      isReserve: false,
      careerWins: 64,
      careerPodiums: 116,
      careerStarts: 218,
      worldTitles: 4,
      attributes: { pace: 97, racecraft: 96, experience: 92, mentality: 90, marketability: 95, developmentPotential: 50 },
      peerAttributes: { pace: 84, racecraft: 82, experience: 78, mentality: 74, marketability: 72, developmentPotential: 68 },
      seasonStats: { points: 168, wins: 4, podiums: 6, poles: 3, dnfs: 1, penalties: 1, bestFinish: 1, averageFinish: 2.4 },
      championshipPosition: 2,
      championshipGap: -14,
      pulse: { headline: "On championship pace", detail: "4 wins in 8 · trailing leader by 14 pts · DNF in Monaco the only blemish" },
      form: [1, 2, 1, 3, 1, 22, 1, 2],
      lastRaceResult: 2,
      mood: { motivation: 92, confidence: 95, frustration: 28 },
      rivalries: [
        { code: "NOR", team: "McLaren", name: "L. Norris", cause: "Title fight · multiple flashpoints", intensity: 84 },
        { code: "RUS", team: "Mercedes", name: "G. Russell", cause: "Q3 contact · R06 Barcelona", intensity: 52 },
      ],
      contract: {
        salary: 55000000,
        termEndSeason: 3,
        releaseClause: null,
        performanceBonuses: [
          { condition: "Per win", value: 750000 },
          { condition: "World Championship", value: 5000000 },
        ],
      },
      penaltyPoints: [
        { points: 2, offenceType: "causingCollision", issuedSeason: 2026, issuedRound: 5 },
      ],
      warningsThisSeason: 1,
      banUntilRound: null,
      nextRaceGridDrop: 0,
    },
    {
      slot: "CAR-02",
      firstName: "Saoirse",
      lastName: "Halloran",
      shortName: "HAL",
      natCode: "IRL",
      age: 22,
      raceNumber: 44,
      isReserve: false,
      attributes: { pace: 85, racecraft: 76, experience: 58, mentality: 70, marketability: 78, developmentPotential: 92 },
      peerAttributes: { pace: 84, racecraft: 82, experience: 78, mentality: 74, marketability: 72, developmentPotential: 68 },
      seasonStats: { points: 31, wins: 0, podiums: 0, poles: 0, dnfs: 2, penalties: 4, bestFinish: 5, averageFinish: 9.8 },
      championshipPosition: 12,
      championshipGap: -137,
      pulse: { headline: "Rookie campaign — finding rhythm", detail: "P5 best · 4 penalties accumulating · qualifying pace ahead of race-day delivery" },
      form: [11, 8, 22, 7, 14, 9, 10, 12],
      lastRaceResult: 12,
      mood: { motivation: 84, confidence: 52, frustration: 64 },
      rivalries: [
        { code: "DEL", team: "Cobalt Motorsport", name: "R. Delacroix", cause: "Last-lap contact · R07 Monaco", intensity: 81 },
      ],
      contract: {
        salary: 2200000,
        termEndSeason: 3,
        releaseClause: null,
        performanceBonuses: [
          { condition: "First career win", value: 1000000 },
          { condition: "Rookie of the Year", value: 750000 },
        ],
      },
      penaltyPoints: [
        { points: 3, offenceType: "causingCollision", issuedSeason: 2026, issuedRound: 7 },
        { points: 2, offenceType: "speedingPitLane", issuedSeason: 2026, issuedRound: 5 },
        { points: 2, offenceType: "ignoredFlags", issuedSeason: 2026, issuedRound: 3 },
        { points: 1, offenceType: "excessiveTrackLimits", issuedSeason: 2025, issuedRound: 21 },
      ],
      warningsThisSeason: 4,
      banUntilRound: null,
      nextRaceGridDrop: 3,
    },
    {
      slot: "RESERVE",
      firstName: "Tomás",
      lastName: "Reyes",
      shortName: "REY",
      natCode: "MEX",
      age: 24,
      raceNumber: 31,
      isReserve: true,
      attributes: { pace: 78, racecraft: 74, experience: 45, mentality: 72, marketability: 60, developmentPotential: 80 },
      peerAttributes: { pace: 76, racecraft: 72, experience: 56, mentality: 68, marketability: 62, developmentPotential: 72 },
      seasonStats: { points: 0, wins: 0, podiums: 0, poles: 0, dnfs: 0, penalties: 0, bestFinish: null, averageFinish: 0 },
      championshipPosition: null,
      championshipGap: null,
      pulse: { headline: "Reserve · race-ready", detail: "Simulator pace within 0.3s of race driver · awaiting call-up window" },
      form: [],
      lastRaceResult: null,
      mood: { motivation: 88, confidence: 64, frustration: 22 },
      rivalries: [],
      contract: {
        salary: 600000,
        termEndSeason: 1,
        releaseClause: null,
        performanceBonuses: [
          { condition: "Per race start", value: 80000 },
        ],
      },
      penaltyPoints: [],
      warningsThisSeason: 0,
      banUntilRound: null,
      nextRaceGridDrop: 0,
    },
  ],
  scouts: [
    {
      id: "yoshida",
      firstName: "Aiko",
      lastName: "Yoshida",
      shortName: "YOS",
      nat: "JPN",
      age: 20,
      isF2: true,
      scouted: 14,
      attributes: { pace: 86, racecraft: 78, experience: 38, mentality: 72, marketability: 82, developmentPotential: 95 },
      askingSalary: 1800000,
      signal: "hot",
    },
    {
      id: "novak",
      firstName: "Mateo",
      lastName: "Novák",
      shortName: "NVK",
      nat: "CZE",
      age: 19,
      isF2: true,
      scouted: 9,
      attributes: { pace: 80, racecraft: 70, experience: 28, mentality: 76, marketability: 58, developmentPotential: 88 },
      askingSalary: 900000,
      signal: "tracking",
    },
    {
      id: "ferrara",
      firstName: "Giulio",
      lastName: "Ferrara",
      shortName: "FRR",
      nat: "ITA",
      age: 33,
      isF2: false,
      scouted: 6,
      attributes: { pace: 82, racecraft: 90, experience: 95, mentality: 80, marketability: 70, developmentPotential: 30 },
      askingSalary: 5500000,
      signal: "available",
    },
    {
      id: "abiola",
      firstName: "Femi",
      lastName: "Abiola",
      shortName: "ABI",
      nat: "NGA",
      age: 25,
      isF2: false,
      scouted: 4,
      attributes: { pace: 79, racecraft: 81, experience: 68, mentality: 78, marketability: 76, developmentPotential: 65 },
      askingSalary: 3200000,
      signal: "available",
    },
    {
      id: "lindqvist",
      firstName: "Elin",
      lastName: "Lindqvist",
      shortName: "LDQ",
      nat: "SWE",
      age: 21,
      isF2: true,
      scouted: 11,
      attributes: { pace: 83, racecraft: 74, experience: 42, mentality: 80, marketability: 74, developmentPotential: 90 },
      askingSalary: 1400000,
      signal: "tracking",
    },
  ],
};
